kind: Service
apiVersion: v1
metadata: 
  name: example-app
  labels:
    tier: frontend
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort 
  selector: 
    app: example-app 
  ports:
  - name: http
    protocol: TCP
    port: 30000
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: example-app
        version: 1.1.3
    spec:
      containers:
      - name: example-app 
        image: quay.io/fabxc/prometheus_demo_service
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
